### ISSUE TITLE
Local privacy activist supports you

### ISSUE THREAD

**Issue by FreeScholar** [maxvonhippel/isec-sensors-scandal#1]
How best to show our support for the ISEC students?

I have  used the Khoury hallways off Parker St. to educate Boston residents on privacy and surveillance concerns, teaching them to use a laptop safely, etc. and would like to invite students to help build our workshops
https://communitybridge.com/privacy-resources/

**Comment by maxvonhippel** [comment]
Thanks for the support!  I suggest you email me (maxvh@hey.com) and I can put you in touch with other students.
